"""
    Bundesnetzagentur Strommarktdaten

    Bundesnetzagentur Strommarktdaten  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.smard.model.time_series2_series_inner import TimeSeries2SeriesInner
from deutschland.smard.model.time_series_meta_data import TimeSeriesMetaData

from deutschland import smard

globals()["TimeSeries2SeriesInner"] = TimeSeries2SeriesInner
globals()["TimeSeriesMetaData"] = TimeSeriesMetaData
from deutschland.smard.model.time_series2 import TimeSeries2


class TestTimeSeries2(unittest.TestCase):
    """TimeSeries2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeSeries2(self):
        """Test TimeSeries2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TimeSeries2()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
