"""
    Bundesnetzagentur Strommarktdaten

    Bundesnetzagentur Strommarktdaten  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.smard.model.time_series2_series_inner_values_inner_versions_inner import (
    TimeSeries2SeriesInnerValuesInnerVersionsInner,
)

from deutschland import smard

globals()[
    "TimeSeries2SeriesInnerValuesInnerVersionsInner"
] = TimeSeries2SeriesInnerValuesInnerVersionsInner
from deutschland.smard.model.time_series2_series_inner_values_inner import (
    TimeSeries2SeriesInnerValuesInner,
)


class TestTimeSeries2SeriesInnerValuesInner(unittest.TestCase):
    """TimeSeries2SeriesInnerValuesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeSeries2SeriesInnerValuesInner(self):
        """Test TimeSeries2SeriesInnerValuesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TimeSeries2SeriesInnerValuesInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
