"""
    Bundesnetzagentur Strommarktdaten

    Bundesnetzagentur Strommarktdaten  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.smard.model.time_series2_series_inner_values_inner import (
    TimeSeries2SeriesInnerValuesInner,
)

from deutschland import smard

globals()["TimeSeries2SeriesInnerValuesInner"] = TimeSeries2SeriesInnerValuesInner
from deutschland.smard.model.time_series2_series_inner import TimeSeries2SeriesInner


class TestTimeSeries2SeriesInner(unittest.TestCase):
    """TimeSeries2SeriesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeSeries2SeriesInner(self):
        """Test TimeSeries2SeriesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TimeSeries2SeriesInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
