"""
    Bundesnetzagentur Strommarktdaten

    Bundesnetzagentur Strommarktdaten  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.smard.model.time_series2_series_inner_values_inner_versions_inner import (
    TimeSeries2SeriesInnerValuesInnerVersionsInner,
)

from deutschland import smard


class TestTimeSeries2SeriesInnerValuesInnerVersionsInner(unittest.TestCase):
    """TimeSeries2SeriesInnerValuesInnerVersionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeSeries2SeriesInnerValuesInnerVersionsInner(self):
        """Test TimeSeries2SeriesInnerValuesInnerVersionsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TimeSeries2SeriesInnerValuesInnerVersionsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
