"""
    Bundesnetzagentur Strommarktdaten

    Bundesnetzagentur Strommarktdaten  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.smard.model.time_series_meta_data import TimeSeriesMetaData

from deutschland import smard


class TestTimeSeriesMetaData(unittest.TestCase):
    """TimeSeriesMetaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeSeriesMetaData(self):
        """Test TimeSeriesMetaData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TimeSeriesMetaData()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
